/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './browser';
import * as i2 from './transfer-state';
export const BrowserTransferStateModuleNgFactory:i0.NgModuleFactory<i1.BrowserTransferStateModule> = i0.ɵcmf(i1.BrowserTransferStateModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,
          i2.TransferState,i1.getTransferState,([] as any[])),i0.ɵmpd(5120,i0.APP_INITIALIZER,
          (p0_0:any) => {
            return [i1.getTransferInitializer(p0_0)];
          },[i2.TransferState]),i0.ɵmpd(512,i1.BrowserTransferStateModule,i1.BrowserTransferStateModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2tqcy9Db2RlL0FuZ3VsYXJDbGFzcy91bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL2Jyb3dzZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvcGF0cmlja2pzL0NvZGUvQW5ndWxhckNsYXNzL3VuaXZlcnNhbC10cmFuc2Zlci1zdGF0ZS9zcmMvYnJvd3Nlci50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
