/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './server';
import * as i2 from './transfer-state';
import * as i3 from '@angular/platform-server';
export const ServerTransferStateModuleNgFactory:i0.NgModuleFactory<i1.ServerTransferStateModule> = i0.ɵcmf(i1.ServerTransferStateModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.TransferState,i1.ServerTransferState,[i3.PlatformState,i0.RendererFactory2]),
          i0.ɵmpd(512,i1.ServerTransferStateModule,i1.ServerTransferStateModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2tqcy9Db2RlL0FuZ3VsYXJDbGFzcy91bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3NlcnZlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9wYXRyaWNranMvQ29kZS9Bbmd1bGFyQ2xhc3MvdW5pdmVyc2FsLXRyYW5zZmVyLXN0YXRlL3NyYy9zZXJ2ZXIudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
