/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './transfer-state';
import * as i2 from '@angular/http';
export const TransferHttpModuleNgFactory:i0.NgModuleFactory<i1.TransferHttpModule> = i0.ɵcmf(i1.TransferHttpModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i1.TransferHttp,i1.TransferHttp,[i2.Http,i1.TransferState,[2,'TransferStateKey']]),
          i0.ɵmpd(512,i1.TransferHttpModule,i1.TransferHttpModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2tqcy9Db2RlL0FuZ3VsYXJDbGFzcy91bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3RyYW5zZmVyLXN0YXRlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3BhdHJpY2tqcy9Db2RlL0FuZ3VsYXJDbGFzcy91bml2ZXJzYWwtdHJhbnNmZXItc3RhdGUvc3JjL3RyYW5zZmVyLXN0YXRlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
